# è¯¥é…ç½®ç”±æœ¬äººæŸ¥çœ‹æ–‡æ¡£ã€å‚è€ƒä»–äººé…ç½®ä»¥åŠä¸ªäººéœ€æ±‚ç¼–è¾‘ï¼Œéš¾å…æœ‰ä¸åˆç†ä¹‹å¤„ï¼Œå¦‚æœä½ å¯¹è¯¥é…ç½®æœ‰ä»€ä¹ˆå»ºè®®æˆ–æ„è§è¿˜è¯·æŒ‡å‡ºï¼Œæˆ‘ä¼šåŠæ—¶ä¿®æ”¹ï¼Œäº‰å–åšä¸€ä¸ªé€‚åˆå¤§éƒ¨åˆ†äººä½¿ç”¨çš„æ‡’äººé…ç½®
# Telegram channel @ksc666
# å¤§éƒ¨åˆ†é…ç½® å‚è€ƒ @CHIZI-0618 çš„ box4magisk
# è¯¥é…ç½®ä½ åªéœ€è¦ä¿®æ”¹ proxy-providers è®¢é˜…éƒ¨åˆ†å³å¯ç›´æ¥è·‘èµ·æ¥
# è¯¥é…ç½®å·²åœ¨ Androidï¼ˆMagiskï¼‰ã€Windows å¹³å°æµ‹è¯•é€šè¿‡
# å¦‚éœ€è½¬è½½è¯·æ³¨æ˜å‡ºå¤„
# å¤§éƒ¨åˆ†é…ç½®å‘åŠ äº†æ³¨é‡Šï¼Œä½ å¯ä»¥æ ¹æ®è‡ªå·±éœ€æ±‚ä¿®æ”¹

# http-port: 7890 # HTTP(S) ä»£ç†ç«¯å£
# socks-port: 7892 # SOCKS5 ä»£ç†ç«¯å£
mixed-port: 1080 # HTTP(S) å’Œ SOCKS ä»£ç†æ··åˆç«¯å£
redir-port: 7891 # redirect é€æ˜ä»£ç†ç«¯å£ï¼Œä»…èƒ½ä»£ç† TCP æµé‡ï¼Œä»…é€‚ç”¨äº Linux ä»¥åŠ macOS ä½¿ç”¨
tproxy-port: 1536 # tproxy é€æ˜ä»£ç†ç«¯å£ï¼Œå¯ä»¥ä»£ç† TCP ä»¥åŠ UDP æµé‡ï¼Œä»…é™ linux é€‚ç”¨ (Android è®¾å¤‡å±äº Linux è®¾å¤‡ï¼‰

mode: rule # è¿è¡Œæ¨¡å¼ï¼šrule è§„åˆ™åŒ¹é…ï¼›global å…¨å±€ä»£ç†(éœ€è¦åœ¨GLOBALç­–ç•¥ç»„é€‰æ‹©ä»£ç†/ç­–ç•¥)ï¼›direct å…¨å±€ç›´è¿
find-process-mode: strict # è¿›ç¨‹åŒ¹é…æ¨¡å¼ï¼šalways å¼€å¯ï¼Œå¼ºåˆ¶åŒ¹é…æ‰€æœ‰è¿›ç¨‹ï¼›ï¼›strict é»˜è®¤ï¼Œç”± Clash åˆ¤æ–­æ˜¯å¦å¼€å¯ï¼›off ä¸åŒ¹é…è¿›ç¨‹ï¼Œæ¨èåœ¨è·¯ç”±å™¨ä¸Šä½¿ç”¨æ­¤æ¨¡å¼
global-client-fingerprint: random # å…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹ï¼Œå¯é€‰ï¼š"chrome", "firefox", "safari", "iOS", "android", "edge", "360"," qq", "random"ï¼›è‹¥é€‰æ‹© "random", åˆ™æŒ‰ Cloudflare Radar æ•°æ®æŒ‰æ¦‚ç‡ç”Ÿæˆä¸€ä¸ªç°ä»£æµè§ˆå™¨æŒ‡çº¹ã€‚
global-ua: clash.meta # è‡ªå®šä¹‰å¤–éƒ¨èµ„æºä¸‹è½½æ—¶ä½¿ç”¨çš„UA,é»˜è®¤ä¸º clash.meta
log-level: error # æ—¥å¿—çº§åˆ«ï¼šsilent é™é»˜ï¼Œä¸è¾“å‡ºï¼›error ä»…è¾“å‡ºå‘ç”Ÿé”™è¯¯è‡³æ— æ³•ä½¿ç”¨çš„æ—¥å¿—ï¼›warning è¾“å‡ºå‘ç”Ÿé”™è¯¯ä½†ä¸å½±å“è¿è¡Œçš„æ—¥å¿—ï¼Œä»¥åŠ error çº§åˆ«å†…å®¹ï¼›info è¾“å‡ºä¸€èˆ¬è¿è¡Œçš„å†…å®¹ï¼Œä»¥åŠ error å’Œ warning çº§åˆ«çš„æ—¥å¿—ï¼›debug å°½å¯èƒ½çš„è¾“å‡ºè¿è¡Œä¸­æ‰€æœ‰çš„ä¿¡æ¯
allow-lan: true # å…è®¸å±€åŸŸç½‘å†…å…¶ä»–è®¾å¤‡ç»è¿‡ Clash çš„ä»£ç†ç«¯å£è®¿é—®äº’è”ç½‘ï¼Œå¯é€‰å€¼ true/false
bind-address: "*" # ç»‘å®š IP, é€šè¿‡ LAN è®¿é—®ä¸€ä¸ª/ä¸€äº›ç‰¹å®šçš„ IP åœ°å€ï¼Œ"*" ç»‘å®šæ‰€æœ‰ IP åœ°å€ï¼Œé»˜è®¤å€¼ï¼Œä¸å¡«å†™æ­¤é¡¹åˆ™ç»‘å®šå…¨éƒ¨
ipv6: true # æ˜¯å¦å…è®¸å†…æ ¸æ¥å— IPv6 æµé‡ï¼Œå¯é€‰å€¼ true/false
tcp-concurrent: true # tcpå¹¶å‘ï¼Œå…è®¸åŒæ—¶å¤„ç†å¤šä¸ªtcpè¿æ¥ï¼Œå¯é€‰å€¼ true/false
keep-alive-interval: 30 # TCP Keep Alive é—´éš”,å•ä½åˆ†é’Ÿ | æ§åˆ¶ Clash å‘å‡º TCP Keep Alive åŒ…çš„é—´éš”,å‡å°‘ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜çš„ä¸´æ—¶æªæ–½
unified-delay: true # ç»Ÿä¸€å»¶è¿Ÿï¼Œæ›´æ¢å»¶è¿Ÿè®¡ç®—æ–¹å¼,å»é™¤æ¡æ‰‹ç­‰é¢å¤–å»¶è¿Ÿ å¯é€‰å€¼ true/false

# GEOæ–‡ä»¶é…ç½®
geodata-mode: true # GeoIP ä½¿ç”¨çš„æ–‡ä»¶,å¯é€‰ true ä¸º.dat/ false ä¸º.mmdb
geosite-matcher: succinct # GeoSite ä½¿ç”¨çš„åŒ¹é…å™¨å®ç°ï¼Œå¯é€‰ï¼šsuccinctï¼šä¸è§„åˆ™é›†ç›¸åŒï¼›mphï¼šæ¥è‡ª V2Rayï¼Œä¹Ÿæ˜¯ Xray ä¸­çš„â€œæ··åˆâ€
geodata-loader: memconservative # GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼šstandardï¼šæ ‡å‡†åŠ è½½å™¨ï¼›memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™(å°å†…å­˜)è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨(é»˜è®¤å€¼)
geo-auto-update: true # è‡ªåŠ¨æ›´æ–° GEO æ–‡ä»¶,å¯é€‰ true/false
geo-update-interval: 72 # æ›´æ–°é—´éš”,å•ä½ï¼šå°æ—¶
geox-url: # è‡ªå®šä¹‰ GEO æ–‡ä»¶ä¸‹è½½åœ°å€
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

# å¤–éƒ¨æ§åˆ¶ (API)
external-controller: 127.0.0.1:9090 # å¤–éƒ¨æ§åˆ¶å™¨ï¼Œå¯ä»¥ä½¿ç”¨ RESTful API æ¥æ§åˆ¶ä½ çš„ Clash å†…æ ¸ï¼›API ç›‘å¬åœ°å€ï¼Œä½ å¯ä»¥å°† 127.0.0.1 ä¿®æ”¹ä¸º 0.0.0.0 æ¥ç›‘å¬æ‰€æœ‰ IPï¼›è®¿é—®åœ°å€ï¼šhttp://127.0.0.1:9090
# external-controller-tls: 127.0.0.1:9443 # HTTPS-API ç›‘å¬åœ°å€ï¼Œéœ€è¦é…ç½® tls éƒ¨åˆ†è¯ä¹¦å’Œå…¶ç§é’¥é…ç½®ï¼Œä½¿ç”¨ TLS ä¹Ÿå¿…é¡»å¡«å†™ external-controller
secret: "ksc666" # API çš„è®¿é—®å¯†é’¥
external-ui: "./ui" # å¤–éƒ¨ç”¨æˆ·ç•Œé¢è·¯å¾„ï¼Œå¯ä»¥ä¸ºç»å¯¹è·¯å¾„ï¼Œæˆ–è€… Clash å·¥ä½œç›®å½•çš„ç›¸å¯¹è·¯å¾„
external-ui-name: "metacubexd" # è‡ªå®šä¹‰å¤–éƒ¨ç”¨æˆ·ç•Œé¢åå­—
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" # è‡ªå®šä¹‰å¤–éƒ¨ç”¨æˆ·ç•Œé¢ä¸‹è½½åœ°å€

profile: # ç¼“å­˜
  store-selected: true # å‚¨å­˜ API å¯¹ç­–ç•¥ç»„çš„é€‰æ‹©ï¼Œä»¥ä¾›ä¸‹æ¬¡å¯åŠ¨æ—¶ä½¿ç”¨
  store-fake-ip: true # å‚¨å­˜ fakeip æ˜ å°„è¡¨ï¼ŒåŸŸåå†æ¬¡å‘ç”Ÿè¿æ¥æ—¶ï¼Œä½¿ç”¨åŸæœ‰æ˜ å°„åœ°å€

sniffer: # åŸŸåå—…å™¨,é€šè¿‡è¯»å–æ¡æ‰‹åŒ…å†…çš„åŸŸåå­—æ®µ,å°†IPè¿˜åŸæˆåŸŸå,æœ‰æ•ˆè§£å†³Mappingæœºåˆ¶çš„çŸ­æ¿
  enable: true
  force-dns-mapping: true # å¯¹ redir-host ç±»å‹è¯†åˆ«çš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  parse-pure-ip: true # å¯¹æ‰€æœ‰æœªè·å–åˆ°åŸŸåçš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  override-destination: true # æ˜¯å¦ä½¿ç”¨å—…æ¢ç»“æœä½œä¸ºå®é™…è®¿é—®,é»˜è®¤ä¸º true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true # å¯è¦†ç›– sniffer.override-destination
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain: # éœ€è¦å¼ºåˆ¶å—…æ¢çš„åŸŸåï¼ˆé»˜è®¤æƒ…å†µä¸‹åªå¯¹IPè¿›è¡Œå—…æ¢ï¼‰
    - "+.v2ex.com"
  skip-domain: # éœ€è¦è·³è¿‡å—…æ¢çš„åŸŸåã€‚ä¸»è¦è§£å†³éƒ¨åˆ†ç«™ç‚¹sniå­—æ®µéåŸŸåï¼Œå¯¼è‡´å—…æ¢ç»“æœå¼‚å¸¸çš„é—®é¢˜ï¼Œå¦‚ç±³å®¶è®¾å¤‡
    - "Mijia Cloud"

tun:
  enable: false # æ˜¯å¦å¯ç”¨,å¯é€‰ true/false
  stack: mixed # tun æ¨¡å¼å †æ ˆï¼Œå¦‚æ— ä½¿ç”¨é—®é¢˜ï¼Œå»ºè®®ä½¿ç”¨ mixedæ ˆï¼Œé»˜è®¤ gvisorï¼Œå¯ç”¨å€¼ï¼š system/gvisor/mixed
  auto-route: true # è‡ªåŠ¨è®¾ç½®å…¨å±€è·¯ç”±,å¯ä»¥è‡ªåŠ¨å°†å…¨å±€æµé‡è·¯ç”±è¿›å…¥ tun ç½‘å¡
  auto-detect-interface: true # è‡ªåŠ¨é€‰æ‹©æµé‡å‡ºå£æ¥å£,å¤šå‡ºå£ç½‘å¡åŒæ—¶è¿æ¥çš„è®¾å¤‡å»ºè®®æ‰‹åŠ¨æŒ‡å®šå‡ºå£ç½‘å¡
  dns-hijack: # dns åŠ«æŒï¼Œå°†åŒ¹é…åˆ°çš„è¿æ¥å¯¼å…¥å†…éƒ¨ dns æ¨¡å—ï¼Œä¸ä¹¦å†™åè®®åˆ™ä¸º udp://
    - "any:53"
  device: Meta # æŒ‡å®š tun ç½‘å¡åç§°,MacOS è®¾å¤‡åªèƒ½ä½¿ç”¨ utun å¼€å¤´çš„ç½‘å¡å
  mtu: 9000 # æœ€å¤§ä¼ è¾“å•å…ƒï¼Œä¼šå½±å“æé™çŠ¶æ€ä¸‹çš„é€Ÿç‡ï¼Œä¸€èˆ¬ç”¨æˆ·é»˜è®¤å³å¯ã€‚
  strict-route: false # ä¸¥æ ¼è·¯ç”±ï¼Œæ‰€æœ‰è¿æ¥è·¯ç”±åˆ° tun æ¥é˜²æ­¢æ³„æ¼,ä½†è®¾å¤‡å°†æ— æ³•è¢«å…¶ä»–è®¾å¤‡è®¿é—®
  gso: true # å¯ç”¨é€šç”¨åˆ†æ®µå¸è½½,ä»…æ”¯æŒ Linux
  gso-max-size: 65536 # æ•°æ®å—çš„æœ€å¤§é•¿åº¦
  udp-timeout: 300 # UDP NAT è¿‡æœŸæ—¶é—´,ä»¥ç§’ä¸ºå•ä½,é»˜è®¤ä¸º 300(5 åˆ†é’Ÿ)
  endpoint-independent-nat: false # å¯ç”¨ç‹¬ç«‹äºç«¯ç‚¹çš„ NAT,æ€§èƒ½å¯èƒ½ä¼šç•¥æœ‰ä¸‹é™,æ‰€ä»¥ä¸å»ºè®®åœ¨ä¸éœ€è¦çš„æ—¶å€™å¼€å¯
  inet4-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - 192.168.0.0/16
  inet6-route-exclude-address: #å¯ç”¨ auto-route æ—¶æ’é™¤è‡ªå®šä¹‰ç½‘æ®µ
    - fc00::/7

dns:
  enable: true
  prefer-h3: true #ä¼˜å…ˆä½¿ç”¨ DOH çš„ http/3
  listen: 0.0.0.0:1053
  ipv6: true
  ipv6-timeout: 300 #ipv6è¶…æ—¶ï¼Œå•ä½ æ¯«ç§’
  cache-algorithm: arc #ç¼“å­˜ç®—æ³•
  use-hosts: true #æŸ¥è¯¢ç³»ç»ŸHosts
  default-nameserver: #é»˜è®¤ DNS, ç”¨äºè§£æ DNS æœåŠ¡å™¨ çš„åŸŸåï¼Œå¿…é¡»ä¸º IP, å¯ä¸ºåŠ å¯† DNS
    - 'https://1.12.12.12/dns-query'
    - 'https://[2400:3200::1]/dns-query'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter: #fakeip è¿‡æ»¤ï¼Œä»¥ä¸‹åœ°å€ä¸ä¼šä¸‹å‘ fakeip æ˜ å°„ç”¨äºè¿æ¥
    - '*'
    - '+.lan'
    - '+.local'
  nameserver-policy: ##æŒ‡å®šåŸŸåæŸ¥è¯¢çš„è§£ææœåŠ¡å™¨ï¼Œä¼˜å…ˆäº nameserver/fallback æŸ¥è¯¢
    "geosite:cn,private":
      - 'https://1.12.12.12/dns-query'
      - 'https://223.5.5.5/dns-query'
      - 'https://[2400:3200::1]/dns-query'
      - 'https://[2402:4e00::]/dns-query'
  nameserver: #é»˜è®¤çš„åŸŸåè§£ææœåŠ¡å™¨ï¼Œå¦‚ä¸é…ç½® fallback/proxy-server-nameserver , åˆ™æ‰€æœ‰åŸŸåéƒ½ç”± nameserver è§£æ
    - 'https://1.1.1.1/dns-query#ğŸŒDNSè§£æ'
    - 'https://8.8.8.8/dns-query#ğŸŒDNSè§£æ'
    - 'https://[2606:4700:4700::1111]/dns-query#ğŸŒDNSè§£æ'
    - 'https://[2001:4860:4860::8888]/dns-query#ğŸŒDNSè§£æ'
#    - 'https://94.140.14.14/dns-query#ğŸŒDNSè§£æ'
#    - 'https://9.9.9.9/dns-query#ğŸŒDNSè§£æ'
#    - 'https://208.67.222.222/dns-query#ğŸŒDNSè§£æ'
#    - 'https://[2a10:50c0::ad1:ff]/dns-query#ğŸŒDNSè§£æ'
#    - 'https://[2620:fe::fe]/dns-query#ğŸŒDNSè§£æ'
#    - 'https://[2620:119:35::35]/dns-query#ğŸŒDNSè§£æ'
  proxy-server-nameserver: #ä»£ç†èŠ‚ç‚¹åŸŸåè§£ææœåŠ¡å™¨ï¼Œä»…ç”¨äºè§£æä»£ç†èŠ‚ç‚¹çš„åŸŸå
    - 'https://1.1.1.1/dns-query#ğŸŒDNSè§£æ'
    - 'https://8.8.8.8/dns-query#ğŸŒDNSè§£æ'

proxies:
  
# éŒ¨ç‚¹ï¼Œå°†éœ€è¦åå¤ä¹¦å†™çš„é…ç½®è®¾ä¸ºéŒ¨ç‚¹ï¼Œåœ¨éœ€è¦çš„åœ°æ–¹å¼•ç”¨
# è®¢é˜…ç±»å‹ï¼Œæ›´æ–°é—´éš”ï¼Œå¥åº·æ£€æŸ¥é…ç½®
p: &p 
  {type: http, interval: 86400, proxy: ğŸŒä»£ç†, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 3600, timeout: 5000, lazy: true}}

# ç­–ç•¥ç»„
pr: &pr 
  {type: select, proxies: [DIRECT, REJECT, ğŸš€æ‰‹åŠ¨é€‰æ‹©, â™»ï¸è‡ªåŠ¨é€‰æ‹©, ğŸ”¯è´Ÿè½½å‡è¡¡, ğŸ› æ•…éšœè½¬ç§», ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡¹ğŸ‡¼å°æ¹¾, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡ºğŸ‡¸ç¾å›½, ğŸŒå…¶å®ƒåœ°åŒº, ğŸ’ä¸“çº¿, ğŸŒå…¨éƒ¨èŠ‚ç‚¹]}

# èŠ‚ç‚¹ç­›é€‰
u: &u 
  type: url-test
  use:
    - ğŸ›« miaona
    - ğŸ›« é­”æˆ’
    - ğŸ›« æé€Ÿäº‘
    - ğŸ›« é¡¶çº§æœºåœº
    - ğŸ›« é£é¸Ÿäº‘
    - ğŸ›« æ·˜æ°”å…”
  exclude-filter: "å¥—é¤|æµé‡|ç¾¤ç»„|é¢‘é“|å®˜ç½‘|æ¨èä½¿ç”¨|æµ‹è¯•|ç”µæŠ¥" #æ’é™¤æ»¡è¶³å…³é”®è¯æˆ–æ­£åˆ™è¡¨è¾¾å¼çš„èŠ‚ç‚¹
  exclude-type: "http" #æ’é™¤æŒ‡å®šç±»å‹çš„èŠ‚ç‚¹ï¼Œä¸æ”¯æŒæ­£åˆ™è¡¨è¾¾å¼ï¼Œé€šè¿‡ | åˆ†å‰²

proxy-providers:
# æœºåœºè®¢é˜…
# override è¦†å†™èŠ‚ç‚¹å†…å®¹ï¼›additional-prefixï¼šä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šå‰ç¼€ï¼›additional-suffixï¼šä¸ºèŠ‚ç‚¹åç§°æ·»åŠ å›ºå®šåç¼€

  ğŸ›« miaona: {<<: *p, url: "https://miaona.org/#/register?code=C3J67GSL", path: ./æœºåœº/å¯ä¹äº‘.yaml, override: {additional-prefix: "å¯ä¹äº‘ | "}}
  ğŸ›« é­”æˆ’: {<<: *p, url: "https://www.mojie.cyou/#/register?code=YjlCVXjA", path: ./æœºåœº/é­”æˆ’.yaml, override: {additional-prefix: "é­”æˆ’ | "}}
  ğŸ›« æé€Ÿäº‘: {<<: *p, url: "https://512.jsy.lol/#/register?code=KmIpamty", path: ./æœºåœº/æé€Ÿäº‘.yaml, override: {additional-prefix: "æé€Ÿäº‘ | "}}
  ğŸ›« é¡¶çº§æœºåœº: {<<: *p, url: "https://xn--mes358a9urctx.com/#/register?code=wiPXjyYq", path: ./æœºåœº/é¡¶çº§æœºåœº.yaml, override: {additional-prefix: "é¡¶çº§æœºåœº | "}}
  ğŸ›« é£é¸Ÿäº‘: {<<: *p, url: "https://www.feiniaoyun.xyz/#/register?code=1gZX21aI", path: ./æœºåœº/é£é¸Ÿäº‘.yaml, override: {additional-prefix: "é£é¸Ÿäº‘ | "}}
  ğŸ›« æ·˜æ°”å…”: {<<: *p, url: "https://vip.taoqitu.pro/index.html?register=rNh8X1zf", path: ./æœºåœº/æ·˜æ°”å…”.yaml, override: {additional-prefix: "æ·˜æ°”å…” | "}}

proxy-groups: #ä»£ç†ç»„

# æ¨¡å¼é€‰æ‹©
  - {name: ğŸŒDNSè§£æ, <<: *pr}
  - {name: ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿, <<: *pr}
  - {name: ğŸŒä»£ç†, <<: *pr}
  - {name: ğŸš€æ‰‹åŠ¨é€‰æ‹©, type: select, proxies: [DIRECT, REJECT, â™»ï¸è‡ªåŠ¨é€‰æ‹©, ğŸ”¯è´Ÿè½½å‡è¡¡, ğŸ› æ•…éšœè½¬ç§», ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡¹ğŸ‡¼å°æ¹¾, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡ºğŸ‡¸ç¾å›½, ğŸŒå…¶å®ƒåœ°åŒº, ğŸ’ä¸“çº¿, ğŸŒå…¨éƒ¨èŠ‚ç‚¹]}
  - {name: â™»ï¸è‡ªåŠ¨é€‰æ‹©, <<: *u, type: url-test, url: 'https://www.gstatic.com/generate_204', interval: 300, tolerance: 5, lazy: true}
  - {name: ğŸ”¯è´Ÿè½½å‡è¡¡, <<: *u, type: load-balance, strategy: consistent-hashing, url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}
  - {name: ğŸ› æ•…éšœè½¬ç§», type: fallback, proxies: [ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡¹ğŸ‡¼å°æ¹¾, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡ºğŸ‡¸ç¾å›½, ğŸŒå…¶å®ƒåœ°åŒº, ğŸ’ä¸“çº¿, ğŸŒå…¨éƒ¨èŠ‚ç‚¹], url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true}

# strategy:è´Ÿè½½å‡è¡¡ç­–ç•¥
# consistent-hashing å°†ä¼šæŠŠç›¸åŒé¡¶çº§åŸŸåçš„è¯·æ±‚åˆ†é…ç»™ç­–ç•¥ç»„å†…çš„åŒä¸€ä¸ªä»£ç†èŠ‚ç‚¹
# round-robin å°†ä¼šæŠŠæ‰€æœ‰çš„è¯·æ±‚åˆ†é…ç»™ç­–ç•¥ç»„å†…ä¸åŒçš„ä»£ç†èŠ‚ç‚¹

# åº”ç”¨åˆ†æµ
#  - {name: ğŸ›¡IPå±åœ°, <<: *pr}
  - {name: ğŸ””Google FCM, <<: *pr}
  - {name: ğŸ“ºYouTube, <<: *pr}
  - {name: ğŸ“²Telegram, <<: *pr}
  - {name: ğŸ“³Github, <<: *pr}
  - {name: ğŸ¤–äººå·¥æ™ºéšœ, <<: *pr}
  - {name: â“‚ï¸MEGA, <<: *pr}
  - {name: ğŸ”Google, <<: *pr}
  - {name: â“‚ï¸Microsoft, <<: *pr}
  - {name: ğŸApple, <<: *pr}
  - {name: ğŸ¦Twitter, <<: *pr}
  - {name: ğŸ…¿ï¸Pixiv, <<: *pr}
  - {name: ğŸ…¿ï¸PikPak, <<: *pr}
  - {name: ğŸ‘›Paypal, <<: *pr}
  - {name: ğŸ®Steam, <<: *pr}
  - {name: ğŸ“¹TikTok, <<: *pr}
  - {name: ğŸ“ºNetflix, <<: *pr}
  - {name: ğŸµSpotify, <<: *pr}
  - {name: â›”ï¸GFW, <<: *pr}
  - {name: ğŸŸæ¼ç½‘ä¹‹é±¼, <<: *pr}

# åœ°åŒºèŠ‚ç‚¹ç­›é€‰
  - {name: ğŸ‡­ğŸ‡°é¦™æ¸¯, <<: *u, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¹ğŸ‡¼å°æ¹¾, <<: *u, filter: "(?i)å°|tw|taiwan|tai"}
  - {name: ğŸ‡¯ğŸ‡µæ—¥æœ¬, <<: *u, filter: "(?i)æ—¥æœ¬|jp|japan"}
  - {name: ğŸ‡ºğŸ‡¸ç¾å›½, <<: *u, filter: "(?i)^(?!.*(?:RU)).*(ç¾|us|unitedstates|united states)"}
  - {name: ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, <<: *u, filter: "(?i)(æ–°|sg|singapore)"}
  - {name: ğŸŒå…¶å®ƒåœ°åŒº, <<: *u, filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¹ğŸ‡¼|æ¸¯|hk|hongkong|hong kong|å°|tw|taiwan|tai|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates)).*"}
  - {name: ğŸ’ä¸“çº¿, <<: *u, filter: "(?i)å¥ˆé£|è§£é”|åŸç”Ÿ|gpt|Netflix"}
  - {name: ğŸŒå…¨éƒ¨èŠ‚ç‚¹, <<: *u}

rule-providers: #å¤–éƒ¨è§„åˆ™æä¾›è€…
  Gemini: {type: http, path: ./rule-providers/Gemini.yaml, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml", interval: 86400, behavior: classical, format: yaml}
  Copilot: {type: http, path: ./rule-providers/Copilot.yaml, url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.yaml", interval: 86400, behavior: classical, format: yaml}
  è‡ªå®šä¹‰ä»£ç†: {type: file, path: ./rule-providers/è‡ªå®šä¹‰ä»£ç†.yaml, behavior: classical, format: yaml}
  è‡ªå®šä¹‰ç›´è¿: {type: file, path: ./rule-providers/è‡ªå®šä¹‰ç›´è¿.yaml, behavior: classical, format: yaml}
# IPå±åœ°
#  anti-ip-attribution: {type: http, path: ./rule-providers/Anti-ip-attribution.yaml, url: "https://raw.githubusercontent.com/lwd-temp/anti-ip-attribution/main/generated/rule-provider.yaml", interval: 86400, behavior: classical, format: yaml}

rules:
# è·¯ç”±è§„åˆ™
# è§„åˆ™å°†æŒ‰ç…§ä»ä¸Šåˆ°ä¸‹çš„é¡ºåºåŒ¹é…ï¼Œåˆ—è¡¨é¡¶éƒ¨çš„è§„åˆ™ä¼˜å…ˆçº§é«˜äºå…¶åº•ä¸‹çš„è§„åˆ™
# å¦‚è¯·æ±‚ä¸º udpï¼Œè€Œä»£ç†èŠ‚ç‚¹æ²¡æœ‰ udp æ”¯æŒ (ä¾‹å¦‚ssèŠ‚ç‚¹æ²¡å†™udp: true),åˆ™ä¼šç»§ç»­å‘ä¸‹åŒ¹é…
# åŸŸåå¼€å§‹åŒ¹é…å…³äº ç›®æ ‡IP è§„åˆ™æ—¶ï¼Œmihomo å°†è§¦å‘ dns è§£ææ¥æ£€æŸ¥åŸŸåçš„ ç›®æ ‡IP æ˜¯å¦åŒ¹é…è§„åˆ™ï¼Œå¯ä»¥é€‰æ‹© no-resolve é€‰é¡¹ä»¥è·³è¿‡ dns è§£æï¼›å¦‚åœ¨æ›´æ—©çš„åŒ¹é…ä¸­è§¦å‘äº† dns è§£æï¼Œåˆ™ä¾æ—§ä¼šåŒ¹é…åˆ°æ·»åŠ äº† no-resolve é€‰é¡¹çš„ ç›®æ ‡IP ç±»è§„åˆ™

# IPå±åœ°
#  - RULE-SET,anti-ip-attribution,ğŸ›¡IPå±åœ°

# ç›´è¿
  - RULE-SET,è‡ªå®šä¹‰ç›´è¿,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,tencent,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,alibaba,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,bytedance,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,xiaomi,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,bilibili,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,category-netdisk-cn,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿

# ä»£ç†
  - GEOSITE,telegram,ğŸ“²Telegram
  - GEOSITE,github,ğŸ“³Github
  - GEOSITE,googlefcm,ğŸ””Google FCM
  - GEOSITE,youtube,ğŸ“ºYouTube
  - RULE-SET,Gemini,ğŸ¤–äººå·¥æ™ºéšœ
  - GEOSITE,google,ğŸ”Google
  - GEOSITE,mega,â“‚ï¸MEGA
  - RULE-SET,è‡ªå®šä¹‰ä»£ç†,ğŸŒä»£ç†
  - GEOSITE,openai,ğŸ¤–äººå·¥æ™ºéšœ
  - RULE-SET,Copilot,ğŸ¤–äººå·¥æ™ºéšœ
  - GEOSITE,microsoft,â“‚ï¸Microsoft
  - GEOSITE,apple,ğŸApple
  - GEOSITE,twitter,ğŸ¦Twitter
  - GEOSITE,pixiv,ğŸ…¿ï¸Pixiv
  - GEOSITE,pikpak,ğŸ…¿ï¸PikPak
  - GEOSITE,steam,ğŸ®Steam
  - GEOSITE,tiktok,ğŸ“¹TikTok
  - GEOSITE,paypal,ğŸ‘›Paypal
  - GEOSITE,netflix,ğŸ“ºNetflix
  - GEOSITE,Spotify,ğŸµSpotify
  - GEOSITE,GFW,â›”ï¸GFW
  - GEOSITE,CN,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOSITE,geolocation-!cn,ğŸŒä»£ç†
  - GEOSITE,private,DIRECT,no-resolve

# GEOIP
  - GEOIP,telegram,ğŸ“²Telegram
  - GEOIP,google,ğŸ”Google
  - GEOIP,twitter,ğŸ¦Twitter
  - GEOIP,netflix,ğŸ“ºNetflix
  - GEOIP,CN,ğŸ‡¨ğŸ‡³å›½å†…ç›´è¿
  - GEOIP,private,DIRECT,no-resolve

# å…œåº•è§„åˆ™
  - MATCH,ğŸŸæ¼ç½‘ä¹‹é±¼
